apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-restapp
  labels: #optional
    app: backend-restapp 
    tier: backend 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-restapp
  template:
    metadata:
      labels: #mandatory
        app: backend-restapp # same as pod label 
        tier: backend 
    spec: 
      containers:
        - name: backend-restapp
          image: stacksimplify/kube-helloworld:1.0.0
          ports:
            - containerPort: 8080        