apiVersion: v1 # String
kind: Pod # String
metadata: # Dictionary
  name: myapp-pod #
  labels: # Dictionary 
    app: myapp  # Key value paids
spec:
  containers: # List | because containers inside a pod can be multiple. but generally we use onlly 1 container per pod 
    - name: myapp
      image: stacksimplify/kubenginx:1.0.0
      ports: 
        - containerPort: 80


# example in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#pod-v1-core

# to run kubectl apply -f 02-pod-definition.yml
# kubectl get pods

