apiVersion: v1
kind: Service 
metadata:
  name: myapp-pod-loadbalancer-service
spec:
  type: LoadBalancer # LoadBalancer, # ClusterIp, # NodePort
  selector:
    app: myapp # this shouldbe same as pod name. whatever traffic comes to this service is sent to that pod
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port